name: Azure AKS Monitroring With Prometheus and Grafana
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  AKS-Cluster-Monitoring:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: AKS
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: "c9c59e08-342f-4f89-bdc6-2c7820d4e70b"
          tenant-id: "fdd345f9-103a-4dcf-8685-4bde04046f0c"
          subscription-id: "ee3b4c5c-9edb-42c3-a37b-2b5a65fd1c61"
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.85.0
        with:
          terraform_version: latest
          cli_config_credentials_token: "VH2lGQlASgzITA.atlasv1.DfSVv8qa7SwABpudmJ45E0FzsAgNzTPae8r9DqQz3wPi6sBwWZ74Q6Ek18j2hWqNmN8"

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output

      - name: AKS Monitroing Enabler
        run: |
          az aks get-credentials -n "cluster-definite-seahorse" -g "rg-hip-urchin"
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
          rm -rf ~/.kube