name: Create Azure AKS With Terraform
on:
  workflow_dispatch:

jobs:
  AKS-Cluster-Deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          service-principal: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
        terraform_version: latest

      - name: Terraform Init
        id: init
        run: | 
            cd Azure_AKS_Labs/AKS
            terraform init
        working-directory: ./Azure_AKS_Labs/AKS/


      - name: Terraform Validate
        id: validate
        run: |
          cd Azure_AKS_Labs/AKS
          terraform validate
        working-directory: ./Azure_AKS_Labs/AKS/

      - name: Terraform Plan
        id: plan
        run: |
          cd Azure_AKS_Labs/AKS
          terraform plan
        working-directory: ./Azure_AKS_Labs/AKS/
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output

